//Via: https://app.rize.education/courses/8156/resource/1f6287eb-b9a5-4052-9b8c-29e987b37a75?weekId=10972
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import ProductCard from "./components/ProductCard.jsx";
import {Header} from "./components/Header.jsx";
import {Hero} from "./components/Hero.jsx";
import {Footer} from "./components/Footer.jsx";

function App() {
  const [count, setCount] = useState(0)
    //Filler text generated by ChatGPT
  return (
      <div className="app">
          <Header/>

          <main className="main-content">
              <Hero/>

              <ProductCard
                  name="Quantum Compute Starter Kit"
                  description="An introductory quantum computing toolkit designed for students and researchers exploring quantum circuits and algorithms."
                  image="https://placehold.co/600x400"
                  price="$99"
              />

              <ProductCard
                  name="Advanced Simulation Engine"
                  description="A high-performance simulation platform for modeling quantum systems under realistic noise and resource constraints."
                  image="https://placehold.co/600x400"
                  price="$249"
              />

              <ProductCard
                  name="Research Collaboration Suite"
                  description="A collaborative environment for sharing experiments, results, and reproducible quantum research workflows."
                  image="https://placehold.co/600x400"
                  price="$149"
              />
          </main>

          <Footer/>
      </div>
  )
}

export default App
